apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: nginx-config
  files:
  - index.html=configs/index.html
secretGenerator:
- name: nginx-secret
  literals:
  - password=superSecret123
